package com.zero.demos.seata.msa.acl.repository.mapper;

import com.zero.demos.seata.msa.acl.repository.entity.OrderEntity;
import com.zero.demos.seata.msa.acl.repository.entity.OrderEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 23 10:30:53 CST 2023
     */
    long countByExample(OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 23 10:30:53 CST 2023
     */
    int deleteByExample(OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 23 10:30:53 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 23 10:30:53 CST 2023
     */
    int insert(OrderEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 23 10:30:53 CST 2023
     */
    int insertSelective(OrderEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 23 10:30:53 CST 2023
     */
    List<OrderEntity> selectByExample(OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 23 10:30:53 CST 2023
     */
    OrderEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 23 10:30:53 CST 2023
     */
    int updateByExampleSelective(@Param("row") OrderEntity row, @Param("example") OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 23 10:30:53 CST 2023
     */
    int updateByExample(@Param("row") OrderEntity row, @Param("example") OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 23 10:30:53 CST 2023
     */
    int updateByPrimaryKeySelective(OrderEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 23 10:30:53 CST 2023
     */
    int updateByPrimaryKey(OrderEntity row);
}