package com.zero.demos.seata.msc.acl.repository.entity;

/**
 * Database Table Remarks:
 *   product table
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_product
 */
public class ProductEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.id
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.name
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    private String name;

    /**
     * Database Column Remarks:
     *   单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.price
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    private Integer price;

    /**
     * Database Column Remarks:
     *   库存数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.stock
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.create_time
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.update_time
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.id
     *
     * @return the value of t_product.id
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.id
     *
     * @param id the value for t_product.id
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.name
     *
     * @return the value of t_product.name
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.name
     *
     * @param name the value for t_product.name
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.price
     *
     * @return the value of t_product.price
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.price
     *
     * @param price the value for t_product.price
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.stock
     *
     * @return the value of t_product.stock
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.stock
     *
     * @param stock the value for t_product.stock
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.create_time
     *
     * @return the value of t_product.create_time
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.create_time
     *
     * @param createTime the value for t_product.create_time
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.update_time
     *
     * @return the value of t_product.update_time
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.update_time
     *
     * @param updateTime the value for t_product.update_time
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}