package com.zero.demos.seata.msb.acl.repository.entity;

/**
 * Database Table Remarks:
 *   account table
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_account
 */
public class AccountEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.id
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.user_id
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.balance
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    private Integer balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.create_time
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.update_time
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.id
     *
     * @return the value of t_account.id
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.id
     *
     * @param id the value for t_account.id
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.user_id
     *
     * @return the value of t_account.user_id
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.user_id
     *
     * @param userId the value for t_account.user_id
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.balance
     *
     * @return the value of t_account.balance
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.balance
     *
     * @param balance the value for t_account.balance
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.create_time
     *
     * @return the value of t_account.create_time
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.create_time
     *
     * @param createTime the value for t_account.create_time
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.update_time
     *
     * @return the value of t_account.update_time
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.update_time
     *
     * @param updateTime the value for t_account.update_time
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}