package com.zero.demos.seata.msb.acl.repository.mapper;

import com.zero.demos.seata.msb.acl.repository.entity.AccountEntity;
import com.zero.demos.seata.msb.acl.repository.entity.AccountEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    long countByExample(AccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    int deleteByExample(AccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    int insert(AccountEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    int insertSelective(AccountEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    List<AccountEntity> selectByExample(AccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    AccountEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    int updateByExampleSelective(@Param("row") AccountEntity row, @Param("example") AccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    int updateByExample(@Param("row") AccountEntity row, @Param("example") AccountEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    int updateByPrimaryKeySelective(AccountEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Wed Aug 23 10:41:07 CST 2023
     */
    int updateByPrimaryKey(AccountEntity row);
}