package com.zero.demos.seata.msc.acl.repository.mapper;

import com.zero.demos.seata.msc.acl.repository.entity.ProductEntity;
import com.zero.demos.seata.msc.acl.repository.entity.ProductEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    long countByExample(ProductEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    int deleteByExample(ProductEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    int insert(ProductEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    int insertSelective(ProductEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    List<ProductEntity> selectByExample(ProductEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    ProductEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    int updateByExampleSelective(@Param("row") ProductEntity row, @Param("example") ProductEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    int updateByExample(@Param("row") ProductEntity row, @Param("example") ProductEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    int updateByPrimaryKeySelective(ProductEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbg.generated Mon Aug 28 16:31:37 CST 2023
     */
    int updateByPrimaryKey(ProductEntity row);

    int updateProductStock(@Param("id") long id, @Param("count") int count);
}